// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMu-X-3W8Id50km-JRXxvRjkV8Is6Z3aI',
    appId: '1:170656274646:android:cd335530a5b70582b99177',
    messagingSenderId: '170656274646',
    projectId: 'futsal-d3828',
    storageBucket: 'futsal-d3828.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADflsnuB_ZF7i5FRk9Ms17aGKkw05Kh18',
    appId: '1:170656274646:ios:8c75e067564bbcdab99177',
    messagingSenderId: '170656274646',
    projectId: 'futsal-d3828',
    storageBucket: 'futsal-d3828.appspot.com',
    iosBundleId: 'com.example.futsalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADflsnuB_ZF7i5FRk9Ms17aGKkw05Kh18',
    appId: '1:170656274646:ios:8c75e067564bbcdab99177',
    messagingSenderId: '170656274646',
    projectId: 'futsal-d3828',
    storageBucket: 'futsal-d3828.appspot.com',
    iosBundleId: 'com.example.futsalApp',
  );
}
